apiVersion: v1
description: KubeDB Catalog by AppsCode - Catalog for database versions
name: kubedb-catalog
version: v2025.12.15
appVersion: v2025.12.15
home: https://kubedb.com
icon: https://cdn.appscode.com/images/icon/kubedb.png
sources:
- https://github.com/kubedb
maintainers:
- name: appscode
  email: support@appscode.com
