apiVersion: v1
appVersion: v2025.12.15
description: KubeDB Community by AppsCode - Community features for KubeDB
home: https://kubedb.com
icon: https://cdn.appscode.com/images/products/kubedb/kubedb-community-icon.png
maintainers:
- email: support@appscode.com
  name: appscode
name: kubedb-community
sources:
- https://github.com/kubedb
version: v2025.12.15
