apiVersion: v1
appVersion: v2025.12.15
description: Free community features for Stash by AppsCode
home: https://stash.run
icon: https://cdn.appscode.com/images/products/stash/stash-community-icon.png
maintainers:
- email: support@appscode.com
  name: appscode
name: stash-community
sources:
- https://github.com/stashed
version: v2025.12.15
